# Generated by Django 5.1.6 on 2026-01-09 12:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0004_alter_bien_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementLogistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code unique')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_mouvement', models.CharField(choices=[('ENT', 'Entrée'), ('SOR', 'Sortie'), ('TRF', 'Transfert'), ('RET', 'Retour'), ('COR', 'Correction')], max_length=20, verbose_name='Type de mouvement')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('source', models.CharField(choices=[('entrepot', 'Entrepôt'), ('fournisseur', 'Fournisseur'), ('stock_central', 'Stock central'), ('autre', 'Autre')], max_length=50, verbose_name='Source')),
                ('destination_type', models.CharField(choices=[('employe', 'Employé'), ('service', 'Service'), ('stock', 'Stock'), ('autre', 'Autre')], max_length=20, verbose_name='Type de destination')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('justification', models.TextField(blank=True, null=True, verbose_name='Justification / Motif')),
                ('reference_document', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Référence documentaire')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='catalogue.bien')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement logistique',
                'verbose_name_plural': 'Mouvements logistiques',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code')),
                ('quantite_disponible', models.PositiveIntegerField(default=1, verbose_name='Quantité disponible')),
                ('lieu_stockage', models.CharField(choices=[('entrepot1', 'Entrepôt 1'), ('entrepot2', 'Entrepôt 2'), ('stock_central', 'Stock central'), ('autre', 'Autre')], max_length=100, verbose_name='Lieu de stockage')),
                ('date_mise_a_jour', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date de mise à jour')),
                ('statut_bien', models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible')], max_length=20, null=True, verbose_name='Statut du bien')),
                ('unite', models.CharField(choices=[('piece', 'Pièce'), ('boite', 'Boîte'), ('litre', 'Litre'), ('autre', 'Autre')], default='piece', max_length=10, verbose_name='Unité')),
                ('niveau_alerte', models.PositiveIntegerField(default=1, verbose_name="Seuil d'alerte")),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalogue.bien')),
                ('responsable_stock', models.ForeignKey(blank=True, limit_choices_to={'role__nom_role': 'gestionnaire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable du stock')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['lieu_stockage', 'bien'],
                'unique_together': {('bien', 'lieu_stockage')},
            },
        ),
    ]
