# Generated by Django 5.1.6 on 2026-01-09 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementlogistique',
            name='bien',
        ),
        migrations.AddField(
            model_name='mouvementlogistique',
            name='stock',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='inventaire.stock', verbose_name='Stock concerné'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='lieu_stockage',
            field=models.CharField(choices=[('', '- Choisir un lieu -'), ('entrepot1', 'Entrepôt 1'), ('entrepot2', 'Entrepôt 2'), ('stock_central', 'Stock central'), ('autre', 'Autre')], max_length=100, verbose_name='Lieu de stockage'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='statut_bien',
            field=models.CharField(blank=True, choices=[('', '- Choisir un statut -'), ('disponible', 'Disponible'), ('indisponible', 'Indisponible')], max_length=20, null=True, verbose_name='Statut du bien'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unite',
            field=models.CharField(choices=[('', '- Choisir une unité -'), ('piece', 'Pièce'), ('boite', 'Boîte'), ('litre', 'Litre'), ('autre', 'Autre')], default='piece', max_length=10, verbose_name='Unité'),
        ),
    ]
