# Generated by Django 5.1.6 on 2026-01-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_remove_mouvementlogistique_bien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementlogistique',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='statut_bien',
            field=models.CharField(blank=True, choices=[('', '- Choisir un statut -'), ('disponible', 'Disponible'), ('indisponible', 'Indisponible')], default='disponible', max_length=20, null=True, verbose_name='Statut du bien'),
        ),
    ]
