# Generated by Django 5.1.6 on 2025-12-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, choices=[('', 'Sélectionner un type'), ('Bien', 'Biens'), ('Service', 'Services')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Suspendu', 'Suspendu'), ('Inactif', 'Inactif')], default='Actif', max_length=10)),
                ('specialite', models.ManyToManyField(blank=True, related_name='fournisseurs', to='catalogue.souscategorie')),
                ('types', models.ManyToManyField(to='Fournisseur.type')),
            ],
        ),
    ]
