# Generated by Django 5.1.6 on 2025-12-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='nom',
            field=models.CharField(blank=True, choices=[('', 'Sélectionner un type'), ('Biens', 'Biens'), ('Services', 'Services')], max_length=10),
        ),
    ]
