# Generated by Django 5.1.6 on 2025-12-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fournisseur', '0002_alter_type_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='nom',
            field=models.CharField(blank=True, choices=[('', 'Sélectionner un type'), ('Bien', 'Biens'), ('Service', 'Services')], max_length=10),
        ),
    ]
