# Generated by Django 5.1.6 on 2026-05-04 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', 'Selectionnez un type'), ('Bien', 'Bien'), ('Service', 'Service')], default='draft', max_length=10)),
                ('quantite', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_demande', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('type_demande', models.CharField(choices=[('Demandeur', 'Demandeur'), ('Gestionnaire', 'Gestionnaire')], max_length=20)),
                ('nature_demande', models.CharField(choices=[('', 'Selectionnez un type'), ('Bien', 'Bien'), ('Service', 'Service')], max_length=10)),
                ('date_demande', models.DateField(default=datetime.date.today)),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='Demande/fichiers/')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('motif_demande', models.TextField()),
                ('statut_demande', models.CharField(choices=[('', 'Selectionnez un type'), ('En cours', 'En cours'), ('Validée', 'Validée'), ('Rejetée', 'Rejetée'), ('Traitement', 'Traitement'), ('Traitée', 'Traitée')], default='En cours', max_length=50)),
                ('demandes_associees', models.ManyToManyField(blank=True, related_name='regroupee_par', to='Demande.demande')),
            ],
        ),
    ]
