# Generated by Django 5.1.6 on 2025-12-10 12:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_demande', models.CharField(blank=True, default='TEMP', editable=False, max_length=50, unique=True)),
                ('type_demande', models.CharField(choices=[('Demandeur', 'Demandeur'), ('Gestionnaire', 'Gestionnaire')], max_length=20)),
                ('nature_demande', models.CharField(choices=[('', 'Selectionnez un type'), ('Bien', 'Bien'), ('Service', 'Service')], max_length=10)),
                ('date_demande', models.DateField(default=datetime.date.today)),
                ('motif_demande', models.TextField()),
                ('statut_demande', models.CharField(max_length=50)),
                ('demandes_associees', models.ManyToManyField(blank=True, related_name='regroupee_par', to='Demande.demande')),
            ],
        ),
        migrations.CreateModel(
            name='DetailsDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', 'Selectionnez un type'), ('Bien', 'Bien'), ('Service', 'Service')], default='draft', max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('motif', models.TextField(blank=True)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.bien')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demande.demande')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.service')),
            ],
        ),
    ]
