# Generated by Django 5.1.6 on 2026-05-04 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Demande', '0001_initial'),
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailsdemande',
            name='bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.bien'),
        ),
        migrations.AddField(
            model_name='detailsdemande',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demande.demande'),
        ),
        migrations.AddField(
            model_name='detailsdemande',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.service'),
        ),
    ]
