# Generated by Django 5.1.6 on 2025-12-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut_demande',
            field=models.CharField(choices=[('', 'Selectionnez un type'), ('En cours', 'En cours'), ('Validée', 'Validée'), ('Rejetée', 'Rejetée'), ('Traitement', 'Traitement'), ('Traitée', 'Traitée')], default='En cours', max_length=50),
        ),
    ]
