# Generated by Django 5.1.6 on 2025-12-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0002_alter_demande_statut_demande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='code_demande',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
