# Generated by Django 5.1.6 on 2026-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0003_alter_demande_code_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-11 00:00:00'),
            preserve_default=False,
        ),
    ]
