# Generated by Django 5.1.6 on 2026-01-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0004_demande_date_enregistrement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsdemande',
            name='motif',
        ),
        migrations.AddField(
            model_name='demande',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
