# Generated by Django 5.1.6 on 2026-01-11 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0005_remove_detailsdemande_motif_demande_date_mise_a_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_enregistrement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
