# Generated by Django 5.1.6 on 2026-01-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0006_alter_demande_date_enregistrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='date_enregistrement',
            field=models.DateTimeField(default='2026-01-11 00:00:00'),
        ),
    ]
