# Generated by Django 5.1.6 on 2026-01-11 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0007_alter_demande_date_enregistrement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='date_enregistrement',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='date_mise_a_jour',
        ),
    ]
