# Generated by Django 5.1.6 on 2026-01-11 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0008_remove_demande_date_enregistrement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='fichier_joint',
            field=models.FileField(blank=True, null=True, upload_to='Demande/fichiers/'),
        ),
        migrations.AddField(
            model_name='demande',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL),
        ),
    ]
