# Generated by Django 5.1.6 on 2026-01-13 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0009_demande_fichier_joint_demande_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demande',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
    ]
