# Generated by Django 5.1.6 on 2026-01-09 12:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Demande', '0003_alter_demande_code_demande'),
        ('Fournisseur', '0003_alter_type_nom'),
        ('catalogue', '0004_alter_bien_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cmnd', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('date_cmnd', models.DateField(default=datetime.date.today)),
                ('statut_cmnd', models.CharField(choices=[('en_cours', 'En Cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], max_length=20)),
                ('fichier_bon_cmnd', models.FileField(blank=True, null=True, upload_to='Commandes/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demande.demande')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fournisseur.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', 'Sélectionner un type'), ('Bien', 'Biens'), ('Service', 'Services')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.bien')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.commande')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.service')),
            ],
        ),
    ]
