# Generated by Django 5.1.6 on 2026-05-04 18:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Demande', '0001_initial'),
        ('Fournisseur', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cmnd', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('date_cmnd', models.DateField(default=datetime.date.today)),
                ('statut_cmnd', models.CharField(choices=[('en_cours', 'En Cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], max_length=20)),
                ('fichier_bon_cmnd', models.FileField(blank=True, null=True, upload_to='Commandes/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demande.demande')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fournisseur.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', 'Sélectionner un type'), ('Bien', 'Bien'), ('Service', 'Service')], max_length=10)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.bien')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commande.commande')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.service')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_livraison', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('date_livraison', models.DateField(default=datetime.date.today)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('partielle', 'Partielle'), ('complete', 'Complète'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('fichier_bon_livraison', models.FileField(blank=True, null=True, upload_to='Livraisons/')),
                ('observation', models.TextField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='commande.commande')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
