# Generated by Django 5.1.6 on 2026-01-10 03:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commande.commande'),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='type',
            field=models.CharField(choices=[('', 'Sélectionner un type'), ('Bien', 'Bien'), ('Service', 'Service')], max_length=10),
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_livraison', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('date_livraison', models.DateField(default=datetime.date.today)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('partielle', 'Partielle'), ('complete', 'Complète'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('fichier_bon_livraison', models.FileField(blank=True, null=True, upload_to='Livraisons/')),
                ('observation', models.TextField(blank=True, null=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='commande.commande')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
