"""
Django settings for monprojet project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)&jyn)ilen$x$p^flp41f1-8-k_wnsyy)udh*c53g^q&8u2=)t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# j'ai ajouté cette ligne (plus pécisément "*")pour autoriser toutes les adresses IP à accéder à l'application pendant le développement
ALLOWED_HOSTS = ["*"]

# Liste des adresses autorisées pour les requêtes POST sécurisées (CSRF)
# Ici on autorise ton serveur local accessible depuis le réseau
# IMPORTANT : doit contenir le protocole + IP + port
#CSRF_TRUSTED_ORIGINS = [
#    "http://192.168.29.152:8080" # Remplace par l'adresse IP et le port de ton serveur local
#]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monprojet',
    'monBlog',
    'Demande',
    'Fournisseur',
    'catalogue',
    'accounts',
    'commande',
    'inventaire',
    'django_select2',
    'crispy_forms',
    'crispy_bootstrap5',

]
# Définir le template pack par défaut
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = 'accounts:connexion'
LOGIN_REDIRECT_URL = 'accounts:dashboard'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Ajout de WhiteNoise pour servir les fichiers statiques en production

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'monprojet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'monprojet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
# Répertoire de stockage des fichiers médias (images, fichiers, etc.)
MEDIA_URL = '/media/'  # URL publique pour accéder aux fichiers
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Dossier physique sur le serveur où les fichiers seront stockés

STATIC_ROOT = BASE_DIR / "staticfiles"  # Dossier de collecte des fichiers statiques pour la production
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Dossier des fichiers statiques principaux
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
