# Generated by Django 5.1.6 on 2026-05-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20)),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20)),
                ('designation', models.CharField(max_length=200)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.famille')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20)),
                ('designation', models.CharField(max_length=200)),
                ('frequence', models.CharField(choices=[('', 'choisissez'), ('hebdomadaire ', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel '), ('ponctuel', 'Ponctuel  ')], default='draft', max_length=20)),
                ('description', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalogue.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20)),
                ('type', models.CharField(blank=True, choices=[('', 'Sélectionner un type'), ('Bien', 'Biens'), ('Service', 'Services')], max_length=10, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='catalogue.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, editable=False, max_length=20)),
                ('designation', models.CharField(max_length=200)),
                ('frequence_utilisation', models.CharField(choices=[('', 'choisissez'), ('hebdomadaire ', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel '), ('ponctuel', 'Ponctuel  '), ('occasionnel', 'Occasionnel  '), ('quotidien', 'Quotidien  '), ('autre', 'Autre  ')], default='draft', max_length=20)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('marque', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marque')),
                ('modele', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modèle')),
                ('informations_complementaires', models.TextField(blank=True, null=True, verbose_name='Informations complémentaires')),
                ('sous_categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='catalogue.souscategorie')),
            ],
        ),
    ]
