# Generated by Django 5.1.6 on 2025-12-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='numero',
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
    ]
