# Generated by Django 5.1.6 on 2026-01-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_bien_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='informations_complementaires',
            field=models.TextField(blank=True, null=True, verbose_name='Informations complémentaires'),
        ),
        migrations.AddField(
            model_name='bien',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='bien',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='bien',
            name='frequence_utilisation',
            field=models.CharField(choices=[('', 'choisissez'), ('hebdomadaire ', 'Hebdomadaire'), ('mensuel', 'Mensuel'), ('annuel', 'Annuel '), ('ponctuel', 'Ponctuel  '), ('occasionnel', 'Occasionnel  '), ('quotidien', 'Quotidien  '), ('autre', 'Autre  ')], default='draft', max_length=20),
        ),
    ]
